### ISSUE TITLE
Reconstrue styling onto JupyterBook

### ISSUE THREAD

**Issue by JohnTigue** [JohnTigue/tigue_com#24]
This is what was worked out previous to this issue:
- Green: #008000
- Red: #aa0000
- Off-black: #??????

**Comment by JohnTigue** [comment]
Ended up with the following for the `prev` and `next` buttons:
```css
.c-page__nav__next, .c-page__nav__prev {
    color: #404040 !important;
    border: #00800020 1px solid;
    background-color: #00800080;
    margin: 6px;
}

.c-page__nav__next:hover, .c-page__nav__prev:hover {
    color: #000000 !important;
    border: #00780020 1px solid;
    background-color: #008000c0;
    margin: 6px;
}
```
